Mvc.Web.Android/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Web.Android.Controllers
{
    /// <summary>
    /// 母版页
    /// </summary>
    public class MasterController : BaseController
    {
        /// <summary>
        /// 设置（版本，设备ID）
        /// </summary>
        public ActionResult SettingsCommon()
        {
            return PartialView();
        }

        /// <summary>
        /// 宣传
        /// </summary>
        public ActionResult XuanChuan()
        {
            if (ViewBag.User.ID == 0)
                return new EmptyResult();
            if (IsNewMember())
                return PartialView();

            return new EmptyResult();
        }
    }
}

Mvc.Web.Android/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/Scripts/jquery.min.js")
    @Scripts.Render("~/Script/Mobile/jquery.mobile.custom.min.js")
    @Scripts.Render("~/Script/JX.js")
    @Styles.Render("~/Content/css/style.css")
    @RenderSection("styles", required: false)
    <script>
        function __fn() {
            var tempW = 750;
            var size = parseInt($(window).width() * 100 / tempW);
            var html = $('html').eq(0);
            $(html).css({ fontSize: size + 'px' });
        }
        __fn();
        window.onresize = function () { __fn(); }
    </script>
</head>
<body>
    @RenderBody()
    
    @RenderSection("scripts", required: false)
</body>
</html>

Mvc.Web.Android/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
    <meta http-equiv="Cache-Control" content="no-cache" />
    <meta name="description" content="中国最专业的女性原创言情小说网站，拥有上万名知名作者签约首发，拥有超过20万部的言情小说书库，是最大的中文女性言情小说网站" />
    <meta name="keywords" content="言情小说阅读,言情小说下载,手机小说,穿越小说，都市小说" />
    @RenderSection("styles", required: false)
    @Styles.Render("~/Css/Css2.css")
    @Scripts.Render("~/Scripts/jQuery.Min.js")
    @Scripts.Render("~/Script/JX.js")
</head>
<body>
    @RenderBody()

    @RenderSection("scripts", required: false)

    @Html.Action("SettingsCommon", "Master")
</body>
</html>